/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package change_a_y_christian_olsen_william_pfaffe.zip.GUI;

import Handlers.ChangeHandler;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class index extends javax.swing.JFrame {

    ChangeHandler handle = new ChangeHandler();

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        setupPHP();
        handle.setCountrySelected("Colombia");

        handle.setCurrentBalance(5000);
        showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
        handle.addGameToCombo(countryCombo);
        healthBar.setForeground(Color.GREEN);
        healthBar.setValue(100);

        countryCombo.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox) e.getSource();
            String currentCountry = (String) combo.getSelectedItem();
            if (currentCountry.equalsIgnoreCase(handle.getCountrySelected())) {
                JOptionPane.showMessageDialog(null, "Cannot smugle drugs to the "
                        + "same country that you are in now!");
            } else {
                handle.setCountrySelected(currentCountry);
                handle.setCountrySelected(currentCountry);
                handle.setList(currentCountry);
                showCocaine.setText(handle.getCocaine() + "$");
                kgCocaine.setText(handle.getCocaineWeight());
                showHeroin.setText(handle.getHeroin() + "$");
                kgHeroin.setText(handle.getHeroinWeight());
                showAmph.setText(handle.getAmphetamine() + "$");
                kgAmph.setText(handle.getAngeldustWeight());
                showAcid.setText(handle.getAcid() + "$");
                kgAcid.setText(handle.getAcidWeight());
                showAngel.setText(handle.getAngeldust() + "$");
                kgAngel.setText(handle.getAngeldustWeight());
                showMeth.setText(handle.getMeth() + "$");
                kgMeth.setText(handle.getMethWeight());
            }

        });

        drugList.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox) e.getSource();
            String currentDrug = (String) combo.getSelectedItem();
            handle.setItem(currentDrug);
            handle.checkDrug(currentDrug);
            System.out.println(currentDrug);

        });

    }

    public void setupPHP() {
        healthBar.setValue(100);
        healthBar.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        countryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonTravelConfirm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelCountryStash = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showCocaine = new javax.swing.JLabel();
        kgCocaine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showHeroin = new javax.swing.JLabel();
        kgHeroin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showAmph = new javax.swing.JLabel();
        kgAmph = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        showAcid = new javax.swing.JLabel();
        kgAcid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        showAngel = new javax.swing.JLabel();
        kgAngel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        showMeth = new javax.swing.JLabel();
        kgMeth = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        drugList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        amountBuy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelPlayerStash = new javax.swing.JPanel();
        jPanelPlayerDrugList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        sellInv = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSell = new javax.swing.JTextField();
        jButtonSell = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        showBalance = new javax.swing.JLabel();
        healthBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        showCurrentCountry = new javax.swing.JLabel();
        buyHealth = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        buyAgents = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        countryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country" }));

        jLabel1.setText("Choose which country to travel to:");

        jButtonTravelConfirm.setText("Travel");
        jButtonTravelConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTravelConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTravelConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTravelConfirm))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country's Drug List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanelCountryStash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Cocaine");

        jLabel6.setText("Heroin");

        jLabel9.setText("Amphetamine");

        jLabel12.setText("Acid");

        jLabel15.setText("Angel Dust");

        jLabel19.setText("Crystal Meth");

        jLabel28.setText("Current Amount(In Kg)");

        javax.swing.GroupLayout jPanelCountryStashLayout = new javax.swing.GroupLayout(jPanelCountryStash);
        jPanelCountryStash.setLayout(jPanelCountryStashLayout);
        jPanelCountryStashLayout.setHorizontalGroup(
            jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                        .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showCocaine)
                            .addComponent(showHeroin)
                            .addComponent(showAmph)
                            .addComponent(showAcid)
                            .addComponent(showAngel)
                            .addComponent(showMeth))
                        .addGap(79, 79, 79)
                        .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kgMeth)
                            .addComponent(kgAngel)
                            .addComponent(kgAcid)
                            .addComponent(kgAmph)
                            .addComponent(kgHeroin)
                            .addComponent(kgCocaine)
                            .addComponent(jLabel28)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCountryStashLayout.setVerticalGroup(
            jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCocaine)
                    .addComponent(kgCocaine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHeroin)
                    .addComponent(kgHeroin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAmph)
                    .addComponent(kgAmph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAcid)
                    .addComponent(kgAcid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAngel)
                    .addComponent(kgAngel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kgMeth)
                    .addComponent(showMeth))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        drugList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Drug", "Cocaine", "Heroin", "Amphetamine", "Acid", "Angel Dust", "Crystal Meth" }));
        drugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Enter Amount To Buy");

        amountBuy.setToolTipText("Enter amount to buy");
        amountBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountBuyActionPerformed(evt);
            }
        });

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCountryStash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(amountBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCountryStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(amountBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPlayerStash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player Stash", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanelPlayerDrugList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanelPlayerDrugListLayout = new javax.swing.GroupLayout(jPanelPlayerDrugList);
        jPanelPlayerDrugList.setLayout(jPanelPlayerDrugListLayout);
        jPanelPlayerDrugListLayout.setHorizontalGroup(
            jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPlayerDrugListLayout.setVerticalGroup(
            jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Enter amount to sell");

        jButtonSell.setText("Sell");

        javax.swing.GroupLayout jPanelPlayerStashLayout = new javax.swing.GroupLayout(jPanelPlayerStash);
        jPanelPlayerStash.setLayout(jPanelPlayerStashLayout);
        jPanelPlayerStashLayout.setHorizontalGroup(
            jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayerStashLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellInv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                .addGroup(jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanelPlayerDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayerStashLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButtonSell, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPlayerStashLayout.setVerticalGroup(
            jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPlayerDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sellInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        showBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showBalance.setText("Current balance: ");

        healthBar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Player Health");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(healthBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showBalance)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showBalance)
                .addContainerGap())
        );

        jButton2.setText("Options");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HighScores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Total Days Played: ");

        showCurrentCountry.setText("Current Country: Colombia");

        buyHealth.setText("Buy");
        buyHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyHealthActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Buy Health! (600$ Per 10%)");

        buyAgents.setText("Purchase");
        buyAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAgentsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Buy Special Agents!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCurrentCountry)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyAgents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(buyHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCurrentCountry)
                    .addComponent(buyHealth)
                    .addComponent(buyAgents))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPlayerStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPlayerStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugListActionPerformed

    }//GEN-LAST:event_drugListActionPerformed

    private void jButtonTravelConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTravelConfirmActionPerformed

        //Player needs to start in Colombia
        //ONLY these contries can be in the game, NO EXCEPTIONS OR MORE!
        // Denmark, Colombia, Germany, USA, France, Afghanistan
        //First turn af the        
        int dialogButton = JOptionPane.showConfirmDialog(null, "Would you like to end "
                + "your business in this country, end your your turn and travel to "
                + "another country?", "End of Turn", JOptionPane.YES_NO_OPTION);
        System.out.println(dialogButton);
        if (dialogButton == 0) {
            JOptionPane.showMessageDialog(null, "Traveling to selected country...");
            showCurrentCountry.setText("Current Country: " + handle.getCountrySelected());
            handle.setTurns(handle.getTurns() + 1);
            handle.setCountryTravel(handle.getCountrySelected());
            if (handle.getCaugt(5) == true) {
                JOptionPane.showMessageDialog(null, "You have been caugt by the customs!"
                        + "\n\n The amount of drugs you currently have, "
                        + "will be reduced to half the amount, and you will "
                        + "lose 20% of your current HP!!");
                healthBar.setValue(healthBar.getValue() - 20);
            } else {
                JOptionPane.showMessageDialog(null, "Congratulations! \n\n"
                        + "You have successfully gone through customs. Feel free to sell your drugs!");
                if (handle.getCaugt(65) == true) {
                    JOptionPane.showMessageDialog(null, "Prices have changed since your last review!");
                }
            }
        } else if (dialogButton == 1) {
            JOptionPane.showMessageDialog(null, "Player slected NO and stays in the "
                    + "current country");

        }
    }//GEN-LAST:event_jButtonTravelConfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int currentPrice = Integer.parseInt(amountBuy.getText()) * handle.getItemPrice();
        if (currentPrice > handle.getCurrentBalance()) {
            JOptionPane.showMessageDialog(null, "Insufficient money!");
        } else if (amountBuy.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Empty Value!");

        } else {
            int dialogButton = JOptionPane.showConfirmDialog(null, "Would you like to "
                    + "buy " + amountBuy.getText() + " Kg of " + handle.getItem() + " Drugs for " + currentPrice + "$?", "Confirm Trade",
                    JOptionPane.YES_NO_OPTION);
            System.out.println(dialogButton);
            if (dialogButton == 0) {
                handle.setCurrentBalance(handle.getCurrentBalance() - currentPrice);
                showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
                handle.items.add(handle.getItem());
                handle.items.add(amountBuy.getText());
                handle.refreshInventory(jList1);
                handle.refreshJCombo(sellInv);
                JOptionPane.showMessageDialog(null, "Bought " + amountBuy.getText() + " Kg of Drugs for " + currentPrice + " Dollars$. \n\n Your balance is: " + handle.getCurrentBalance(),
                        "Trade Complete", JOptionPane.NO_OPTION);

            } else if (dialogButton == 1) {
                JOptionPane.showMessageDialog(null, "You've cancelled the trade....",
                        "Trade cancelled", JOptionPane.OK_OPTION);

            }

            System.out.println(handle.getAcid());
            System.out.println(handle.getAmphWeight());
            System.out.println(handle.getAngeldust());
            System.out.println(handle.getCocaine());
            System.out.println(handle.getHeroin());
            System.out.println(handle.getMeth());

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void amountBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountBuyActionPerformed

    }//GEN-LAST:event_amountBuyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Opens HighScore Table");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "shows help and describes how to play the game");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buyHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyHealthActionPerformed
        int price = 600;
        if (handle.getCurrentBalance() < price) {
            JOptionPane.showMessageDialog(null, "Insufficient Funds!");
        } else if(healthBar.getValue() >= 100){
        JOptionPane.showMessageDialog(null, "Maximum HP is 100%!");
        } else {
            handle.setCurrentBalance(handle.getCurrentBalance() - price);
            showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
            healthBar.setValue(healthBar.getValue() + 10);
        }
    }//GEN-LAST:event_buyHealthActionPerformed

    private void buyAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAgentsActionPerformed
        int price = 2000;
        if(handle.isAgents() == false){
        JOptionPane.showMessageDialog(null, "Agents offer special abillities, "
                + "such as lowering chances of getting caugt in customs! "
                + "Costly, but efficient");
        
        if (handle.getCurrentBalance() < price) {
            JOptionPane.showMessageDialog(null, "Insufficient Funds!");
        }else if(handle.isAgents() == true){
            JOptionPane.showMessageDialog(null, "You already have an agent working for you!");
        }else{
        handle.setCurrentBalance(handle.getCurrentBalance() - price);
            showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
            handle.setAgents(true);
        }
        }else{
        if (handle.getCurrentBalance() < price) {
            JOptionPane.showMessageDialog(null, "Insufficient Funds!");
        }else if(handle.isAgents() == true){
            JOptionPane.showMessageDialog(null, "You already have an agent working for you!");
        }else{
        handle.setCurrentBalance(handle.getCurrentBalance() - price);
            showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
            handle.setAgents(true);
        }
        }
        

    }//GEN-LAST:event_buyAgentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountBuy;
    private javax.swing.JButton buyAgents;
    private javax.swing.JButton buyHealth;
    private javax.swing.JComboBox<String> countryCombo;
    private javax.swing.JComboBox<String> drugList;
    private javax.swing.JProgressBar healthBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSell;
    private javax.swing.JButton jButtonTravelConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCountryStash;
    private javax.swing.JPanel jPanelPlayerDrugList;
    private javax.swing.JPanel jPanelPlayerStash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSell;
    private javax.swing.JLabel kgAcid;
    private javax.swing.JLabel kgAmph;
    private javax.swing.JLabel kgAngel;
    private javax.swing.JLabel kgCocaine;
    private javax.swing.JLabel kgHeroin;
    private javax.swing.JLabel kgMeth;
    private javax.swing.JComboBox<String> sellInv;
    private javax.swing.JLabel showAcid;
    private javax.swing.JLabel showAmph;
    private javax.swing.JLabel showAngel;
    private javax.swing.JLabel showBalance;
    private javax.swing.JLabel showCocaine;
    private javax.swing.JLabel showCurrentCountry;
    private javax.swing.JLabel showHeroin;
    private javax.swing.JLabel showMeth;
    // End of variables declaration//GEN-END:variables
}
