/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package change_a_y_christian_olsen_william_pfaffe.zip.GUI;

import Handlers.ChangeHandler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author William
 */
public class index extends javax.swing.JFrame {
    ChangeHandler handle = new ChangeHandler();
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        handle.setCurrentBalance(Integer.toString(5000));
        showBalance.setText("Current Balance: " + handle.getCurrentBalance());
        handle.addGameToCombo(countryCombo);
        
        countryCombo.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox)e.getSource();
            String currentCountry = (String)combo.getSelectedItem();
                        handle.setCountrySelected(currentCountry);
                        handle.setList(currentCountry);
                        showCocaine.setText(handle.getCocaine());
                        kgCocaine.setText(handle.getCocaineWeight());
                        showHeroin.setText(handle.getHeroin());
                        kgHeroin.setText(handle.getHeroinWeight());
                        showAmph.setText(handle.getAmphetamine());
                        kgAmph.setText(handle.getAngeldustWeight());
                        showAcid.setText(handle.getAcid());
                        kgAcid.setText(handle.getAcidWeight());
                        showAngel.setText(handle.getAngeldust());
                        kgAngel.setText(handle.getAngeldustWeight());
                        showMeth.setText(handle.getMeth());
                        kgMeth.setText(handle.getMethWeight());
        });
        
        drugList.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox)e.getSource();
            String currentDrug = (String)combo.getSelectedItem();
                       System.out.println(currentDrug);
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showCocaine = new javax.swing.JLabel();
        kgCocaine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showHeroin = new javax.swing.JLabel();
        kgHeroin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showAmph = new javax.swing.JLabel();
        kgAmph = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        showAcid = new javax.swing.JLabel();
        kgAcid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        showAngel = new javax.swing.JLabel();
        kgAngel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        showMeth = new javax.swing.JLabel();
        kgMeth = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        showBalance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        drugList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        countryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country" }));

        jLabel1.setText("Choose which country to smugle to:");

        jLabel3.setText("Enter Amount To Smugle");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Cocaine");

        showCocaine.setText("jLabel4");

        kgCocaine.setText("jLabel5");

        jLabel6.setText("Heroin");

        showHeroin.setText("jLabel7");

        kgHeroin.setText("jLabel8");

        jLabel9.setText("Amphetamine");

        showAmph.setText("jLabel10");

        kgAmph.setText("jLabel11");

        jLabel12.setText("Acid");

        showAcid.setText("jLabel13");

        kgAcid.setText("jLabel14");

        jLabel15.setText("Angel Dust");

        showAngel.setText("jLabel16");

        kgAngel.setText("jLabel17");

        jLabel19.setText("Crystal Meth");

        showMeth.setText("jLabel20");

        kgMeth.setText("jLabel21");

        jLabel28.setText("Current Amount(In Kg)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showCocaine)
                            .addComponent(showHeroin)
                            .addComponent(showAmph)
                            .addComponent(showAcid)
                            .addComponent(showAngel)
                            .addComponent(showMeth))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kgMeth)
                            .addComponent(kgAngel)
                            .addComponent(kgAcid)
                            .addComponent(kgAmph)
                            .addComponent(kgHeroin)
                            .addComponent(kgCocaine)
                            .addComponent(jLabel28)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCocaine)
                    .addComponent(kgCocaine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHeroin)
                    .addComponent(kgHeroin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAmph)
                    .addComponent(kgAmph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAcid)
                    .addComponent(kgAcid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAngel)
                    .addComponent(kgAngel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showMeth)
                    .addComponent(kgMeth))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        showBalance.setText("Current balance: ");

        jButton1.setText("Submit");

        drugList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Drug", "Cocaine", "Heroin", "Amphetamine", "Acid", "Angel Dust", "Crystal Meth" }));
        drugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugListActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Drug");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showBalance)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(countryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(showBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugListActionPerformed
       
    }//GEN-LAST:event_drugListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> countryCombo;
    private javax.swing.JComboBox<String> drugList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kgAcid;
    private javax.swing.JLabel kgAmph;
    private javax.swing.JLabel kgAngel;
    private javax.swing.JLabel kgCocaine;
    private javax.swing.JLabel kgHeroin;
    private javax.swing.JLabel kgMeth;
    private javax.swing.JLabel showAcid;
    private javax.swing.JLabel showAmph;
    private javax.swing.JLabel showAngel;
    private javax.swing.JLabel showBalance;
    private javax.swing.JLabel showCocaine;
    private javax.swing.JLabel showHeroin;
    private javax.swing.JLabel showMeth;
    // End of variables declaration//GEN-END:variables
}
