/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ChangeHandler;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class Gui extends javax.swing.JFrame {

    ChangeHandler handle = new ChangeHandler();
    highScore hs = new highScore();
    Random gen = new Random();

    /**
     * Creates new form index
     */
    public Gui() {
        initComponents();
        setupPlayer();
        handle.setList("Danmark");
        setupDrugs();
        handle.setCocaineB("0");
        handle.setHeroinB("0");
        handle.setAmphB("0");
        handle.setAcidB("0");
        handle.setAngelB("0");
        handle.setMethB("0");
        handle.setCountrySelected("Colombia");
        handle.setTurns(0);
        turnsTotal.setText("0");
        handle.setCurrentBalance(5000);
        showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
        handle.addGameToCombo(countryCombo);
        healthBar.setForeground(Color.GREEN);
        healthBar.setValue(100);

        countryCombo.setSelectedIndex(1);
        handle.setList(countryCombo.getItemAt(1));

        countryCombo.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox) e.getSource();

            String currentCountry = (String) combo.getSelectedItem();
            if (currentCountry.equalsIgnoreCase(handle.getCountrySelected())) {
                JOptionPane.showMessageDialog(null, "Cannot smugle drugs to the "
                        + "same country that you are in now!");
            } else {
                handle.setCountrySelected(currentCountry);
                handle.setList(currentCountry);
                setupDrugs();
            }

        });

        drugList.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox) e.getSource();
            String currentDrug = (String) combo.getSelectedItem();
            handle.setItem(currentDrug);
            handle.checkDrug(currentDrug);
            System.out.println(currentDrug);

        });

        sellInv.addActionListener((ActionEvent e) -> {
            JComboBox combo = (JComboBox) e.getSource();
            String currentDrug = (String) combo.getSelectedItem();
            handle.setItem(currentDrug);
            handle.checkDrug(currentDrug);
            System.out.println(currentDrug);

        });

    }

    public void setupPlayer() {
        String playerName = "";

        while (playerName.isEmpty()) {
            playerName = JOptionPane.showInputDialog("Please enter your player name", "");
            if (playerName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a player name!");

            }
            
            healthBar.setValue(100);
            healthBar.setStringPainted(true);
            handle.setPlayer(playerName);
            showPlayer.setText(playerName + " Health");
        }
    }

    public void setupDrugs() {

        showCocaine.setText(handle.getCocaine() + "$");
        kgCocaine.setText(handle.getCocaineWeight());
        showHeroin.setText(handle.getHeroin() + "$");
        kgHeroin.setText(handle.getHeroinWeight());
        showAmph.setText(handle.getAmphetamine() + "$");
        kgAmph.setText(handle.getAngeldustWeight());
        showAcid.setText(handle.getAcid() + "$");
        kgAcid.setText(handle.getAcidWeight());
        showAngel.setText(handle.getAngeldust() + "$");
        kgAngel.setText(handle.getAngeldustWeight());
        showMeth.setText(handle.getMeth() + "$");
        kgMeth.setText(handle.getMethWeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTravel = new javax.swing.JPanel();
        countryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        commitTravel = new javax.swing.JButton();
        jPanelCountryDrugList = new javax.swing.JPanel();
        jPanelCountryStash = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showCocaine = new javax.swing.JLabel();
        kgCocaine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showHeroin = new javax.swing.JLabel();
        kgHeroin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showAmph = new javax.swing.JLabel();
        kgAmph = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        showAcid = new javax.swing.JLabel();
        kgAcid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        showAngel = new javax.swing.JLabel();
        kgAngel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        showMeth = new javax.swing.JLabel();
        kgMeth = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        drugList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        amountBuy = new javax.swing.JTextField();
        buyDrug = new javax.swing.JButton();
        jPanelPlayerStash = new javax.swing.JPanel();
        jPanelPlayerDrugList = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        heroinKG = new javax.swing.JLabel();
        cocaineKG = new javax.swing.JLabel();
        amphKG = new javax.swing.JLabel();
        acidKG = new javax.swing.JLabel();
        angelKG = new javax.swing.JLabel();
        methKG = new javax.swing.JLabel();
        sellInv = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        sellDrugsText = new javax.swing.JTextField();
        sellDrug = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanelPlayerStats = new javax.swing.JPanel();
        showBalance = new javax.swing.JLabel();
        healthBar = new javax.swing.JProgressBar();
        showPlayer = new javax.swing.JLabel();
        jPanelVarious = new javax.swing.JPanel();
        textShowTurns = new javax.swing.JLabel();
        showCurrentCountry = new javax.swing.JLabel();
        buyHealth = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        buyAgents = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        hasAgents = new javax.swing.JLabel();
        turnsTotal = new javax.swing.JLabel();
        openHighScore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTravel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        countryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country" }));

        jLabel1.setText("Choose which country to travel to:");

        commitTravel.setText("Travel");
        commitTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitTravelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTravelLayout = new javax.swing.GroupLayout(jPanelTravel);
        jPanelTravel.setLayout(jPanelTravelLayout);
        jPanelTravelLayout.setHorizontalGroup(
            jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTravelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelTravelLayout.createSequentialGroup()
                        .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commitTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTravelLayout.setVerticalGroup(
            jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTravelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commitTravel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelCountryDrugList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country's Drug List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPanelCountryStash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Cocaine");

        jLabel6.setText("Heroin");

        jLabel9.setText("Amphetamine");

        jLabel12.setText("Acid");

        jLabel15.setText("Angel Dust");

        jLabel19.setText("Crystal Meth");

        jLabel28.setText("Current Amount(In Kg)");

        javax.swing.GroupLayout jPanelCountryStashLayout = new javax.swing.GroupLayout(jPanelCountryStash);
        jPanelCountryStash.setLayout(jPanelCountryStashLayout);
        jPanelCountryStashLayout.setHorizontalGroup(
            jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                        .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showCocaine)
                            .addComponent(showHeroin)
                            .addComponent(showAmph)
                            .addComponent(showAcid)
                            .addComponent(showAngel)
                            .addComponent(showMeth))
                        .addGap(79, 79, 79)
                        .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kgMeth)
                            .addComponent(kgAngel)
                            .addComponent(kgAcid)
                            .addComponent(kgAmph)
                            .addComponent(kgHeroin)
                            .addComponent(kgCocaine)
                            .addComponent(jLabel28)))
                    .addComponent(jLabel2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelCountryStashLayout.setVerticalGroup(
            jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryStashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCocaine)
                    .addComponent(kgCocaine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHeroin)
                    .addComponent(kgHeroin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAmph)
                    .addComponent(kgAmph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAcid)
                    .addComponent(kgAcid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAngel)
                    .addComponent(kgAngel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCountryStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kgMeth)
                    .addComponent(showMeth))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        drugList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Drug", "Cocaine", "Heroin", "Amphetamine", "Acid", "Angel Dust", "Crystal Meth" }));
        drugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Enter Amount To Buy");

        amountBuy.setToolTipText("Enter amount to buy");
        amountBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountBuyActionPerformed(evt);
            }
        });

        buyDrug.setText("Buy");
        buyDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCountryDrugListLayout = new javax.swing.GroupLayout(jPanelCountryDrugList);
        jPanelCountryDrugList.setLayout(jPanelCountryDrugListLayout);
        jPanelCountryDrugListLayout.setHorizontalGroup(
            jPanelCountryDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                .addComponent(jPanelCountryStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCountryDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(amountBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buyDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelCountryDrugListLayout.setVerticalGroup(
            jPanelCountryDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                .addGroup(jPanelCountryDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelCountryStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCountryDrugListLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(drugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buyDrug)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPlayerStash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player Stash", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPanelPlayerDrugList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Heroin:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cocaine:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Amphetamine:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Acid:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Angel Dust:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Crystal Meth:");

        heroinKG.setText("0");

        cocaineKG.setText("0");

        amphKG.setText("0");

        acidKG.setText("0");

        angelKG.setText("0");

        methKG.setText("0");

        javax.swing.GroupLayout jPanelPlayerDrugListLayout = new javax.swing.GroupLayout(jPanelPlayerDrugList);
        jPanelPlayerDrugList.setLayout(jPanelPlayerDrugListLayout);
        jPanelPlayerDrugListLayout.setHorizontalGroup(
            jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amphKG))
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heroinKG))
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cocaineKG))
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acidKG))
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angelKG))
                    .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(methKG)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelPlayerDrugListLayout.setVerticalGroup(
            jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerDrugListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(heroinKG))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cocaineKG))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(amphKG))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(acidKG))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(angelKG))
                .addGap(18, 18, 18)
                .addGroup(jPanelPlayerDrugListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(methKG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sellInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellInvActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Enter amount to sell");

        sellDrugsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellDrugsTextActionPerformed(evt);
            }
        });

        sellDrug.setText("Sell");
        sellDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellDrugActionPerformed(evt);
            }
        });

        jLabel27.setText("         [NAME]       [KG]");

        javax.swing.GroupLayout jPanelPlayerStashLayout = new javax.swing.GroupLayout(jPanelPlayerStash);
        jPanelPlayerStash.setLayout(jPanelPlayerStashLayout);
        jPanelPlayerStashLayout.setHorizontalGroup(
            jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                        .addComponent(jPanelPlayerDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sellDrugsText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4))
                                .addComponent(sellInv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sellDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelPlayerStashLayout.setVerticalGroup(
            jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlayerStashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPlayerDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPlayerStashLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(sellInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellDrugsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellDrug)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPlayerStats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player Stats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        showBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showBalance.setText("Current balance: ");

        healthBar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        showPlayer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        showPlayer.setText("Player Health");

        javax.swing.GroupLayout jPanelPlayerStatsLayout = new javax.swing.GroupLayout(jPanelPlayerStats);
        jPanelPlayerStats.setLayout(jPanelPlayerStatsLayout);
        jPanelPlayerStatsLayout.setHorizontalGroup(
            jPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlayerStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(healthBar, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addGroup(jPanelPlayerStatsLayout.createSequentialGroup()
                        .addGroup(jPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showBalance)
                            .addComponent(showPlayer))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPlayerStatsLayout.setVerticalGroup(
            jPanelPlayerStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlayerStatsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showBalance)
                .addContainerGap())
        );

        jPanelVarious.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textShowTurns.setText("Total Days Played: ");

        showCurrentCountry.setText("Current Country: Denmark");

        buyHealth.setText("Buy");
        buyHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyHealthActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Buy Health! (600$ Per 10%)");

        buyAgents.setText("Purchase");
        buyAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAgentsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Buy Special Agents! (2000$)");

        hasAgents.setText("Agents Are Inactive!");

        turnsTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        turnsTotal.setText("jLabel7");

        openHighScore.setText("HighScores");
        openHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openHighScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVariousLayout = new javax.swing.GroupLayout(jPanelVarious);
        jPanelVarious.setLayout(jPanelVariousLayout);
        jPanelVariousLayout.setHorizontalGroup(
            jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariousLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hasAgents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showCurrentCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVariousLayout.createSequentialGroup()
                        .addComponent(textShowTurns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turnsTotal)))
                .addGap(123, 123, 123)
                .addGroup(jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(buyAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVariousLayout.createSequentialGroup()
                        .addComponent(buyHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(openHighScore)
                .addGap(46, 46, 46))
        );
        jPanelVariousLayout.setVerticalGroup(
            jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVariousLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textShowTurns)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(turnsTotal))
                .addGap(7, 7, 7)
                .addGroup(jPanelVariousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyHealth)
                    .addComponent(buyAgents)
                    .addComponent(showCurrentCountry)
                    .addComponent(openHighScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasAgents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelVarious, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelCountryDrugList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelPlayerStash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jPanelPlayerStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPlayerStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVarious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCountryDrugList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPlayerStash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugListActionPerformed

    }//GEN-LAST:event_drugListActionPerformed

    private void commitTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitTravelActionPerformed

        if (handle.getTurns() < 19) {
            int chance = 5;
            if (handle.isAgents() == true) {
                chance = 3;
            }

            //ONLY these contries can be in the game, NO EXCEPTIONS OR MORE!
            // Denmark, Colombia, Germany, USA, France, Afghanistan
            //First turn af the        
            int dialogButton = JOptionPane.showConfirmDialog(null, "Would you like to end "
                    + "your business in this country, end your your turn and travel to "
                    + "another country?", "End of Turn", JOptionPane.YES_NO_OPTION);
            System.out.println(dialogButton);
            if (dialogButton == 0) {
                JOptionPane.showMessageDialog(null, "Traveling to selected country...");
                handle.setTurns(handle.getTurns() + 1);
                turnsTotal.setText(Integer.toString(handle.getTurns()));
                showCurrentCountry.setText("Current Country: " + handle.getCountrySelected());
                handle.setCountryTravel(handle.getCountrySelected());
                if (handle.getCaugt(chance) == true) {
                    JOptionPane.showMessageDialog(null, "You have been caugt by the customs!"
                            + "\n\n The amount of drugs you currently have, "
                            + "will be reduced to half the amount, and you will "
                            + "lose 20% of your current HP!!");

                    healthBar.setValue(healthBar.getValue() - 20);

                    //Kontrol af Drugs inden spilleren tages i Tolden:
                    System.out.println("Drugs going into the Toll both: "
                            + "\nCocaine: " + handle.getCocaineB()
                            + "\nAcid: " + handle.getAcidB()
                            + "\nAmp: " + handle.getAmphB()
                            + "\nHeroin: " + handle.getHeroinB()
                            + "\nAngel Dust: " + handle.getAngelB()
                            + "\nMeth: " + handle.getMethB());

                    if ((Integer.parseInt(handle.getCocaineB()) > 1)) {
                        handle.setCocaineB(Integer.toString(Integer.parseInt(handle.getCocaineB()) / 2));
                        cocaineKG.setText(handle.getCocaineB());
                    }
                    if (Integer.parseInt(handle.getAcidB()) > 1) {
                        handle.setAcidB(Integer.toString(Integer.parseInt(handle.getAcidB()) / 2));
                        acidKG.setText(handle.getAcidB());
                    }
                    if (Integer.parseInt(handle.getAmphB()) > 1) {
                        handle.setAmphB(Integer.toString(Integer.parseInt(handle.getAmphB()) / 2));
                        amphKG.setText(handle.getAmphB());
                    }
                    if (Integer.parseInt(handle.getHeroinB()) > 1) {
                        handle.setHeroinB(Integer.toString(Integer.parseInt(handle.getHeroinB()) / 2));
                        heroinKG.setText(handle.getHeroinB());
                    }
                    if (Integer.parseInt(handle.getAngelB()) > 1) {
                        handle.setAngeldust(Integer.toString(Integer.parseInt(handle.getAngelB()) / 2));
                        angelKG.setText(handle.getAngelB());
                    }
                    if (Integer.parseInt(handle.getMethB()) > 1) {
                        handle.setMethB(Integer.toString(Integer.parseInt(handle.getMethB()) / 2));
                        methKG.setText(handle.getMethB());

                    }

                    //Efter spilleren har været i tolden:
                    System.out.println("Drugs going out of the Toll both: "
                            + "\nCocaine: " + handle.getCocaineB()
                            + "\nAcid: " + handle.getAcidB()
                            + "\nAmp: " + handle.getAmphB()
                            + "\nHeroin: " + handle.getHeroinB()
                            + "\nAngel Dust: " + handle.getAngelB()
                            + "\nMeth: " + handle.getMethB());

                    //Metode til at udregne hvor mange stoffer der skal fjernes fra spilleren, 
                    //baseret på et Random tal, som i sig selv er baseret på antal af stoffer som spilleren har!
//                    if(Integer.parseInt(handle.getCocaineB()) >= 1){
//                    handle.setCocaineB(Integer.toString(Integer.parseInt(handle.getCocaineB()) - gen.nextInt(Integer.parseInt(handle.getCocaineB()))+1));
//                    cocaineKG.setText(handle.getCocaineB());
//                    } if(Integer.parseInt(handle.getAcidB()) >= 1){
//                         handle.setAcidB(Integer.toString(Integer.parseInt(handle.getAcidB()) - gen.nextInt(Integer.parseInt(handle.getAcidB()))) +1 );
//                    acidKG.setText(handle.getAcidB());
//                    } if (Integer.parseInt(handle.getAmphB()) >= 1 ){
//                        handle.setAmphB(Integer.toString(Integer.parseInt(handle.getAmphB()) - gen.nextInt(Integer.parseInt(handle.getAmphB()))) +1 );
//                   amphKG.setText(handle.getAmphB());
//                    } if (Integer.parseInt(handle.getHeroinB()) >= 1 ){
//                        handle.setHeroinB(Integer.toString(Integer.parseInt(handle.getHeroinB()) - gen.nextInt(Integer.parseInt(handle.getHeroinB()))) +1 );
//                   heroinKG.setText(handle.getHeroinB());
//                    } if (Integer.parseInt(handle.getAngelB()) >= 1 ){
//                        handle.setAngeldust(Integer.toString(Integer.parseInt(handle.getAngelB()) - gen.nextInt(Integer.parseInt(handle.getAngelB()))) +1 );
//                    angelKG.setText(handle.getAngelB());
//                    } if (Integer.parseInt(handle.getMethB()) >= 1 ){
//                        handle.setMethB(Integer.toString(Integer.parseInt(handle.getMethB()) - gen.nextInt(Integer.parseInt(handle.getMethB()))) +1 );
//                    methKG.setText(handle.getMethB());
//                    }
//                    
                    if (healthBar.getValue() > 70) {
                        healthBar.setForeground(Color.GREEN);
                    } else if (healthBar.getValue() > 40 && healthBar.getValue() > 70) {
                        healthBar.setForeground(Color.ORANGE);
                    } else if (healthBar.getValue() < 40) {
                        healthBar.setForeground(Color.RED);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Congratulations! \n\n"
                            + "You have successfully gone through customs. Feel free to sell your drugs!");

                    if (handle.getCaugt(65) == true) {
                        JOptionPane.showMessageDialog(null, "Prices have changed since your last review!");
                        if (handle.priceUpOrDown() == false) {
                            JOptionPane.showMessageDialog(null, "Prices have decreased");
                            handle.newPriceDown();
                            showAcid.setText(handle.getAcid());
                        } else {
                            JOptionPane.showMessageDialog(null, "Prices have increased");
                            handle.newPriceUp();
                            showAcid.setText(handle.getAcid());
                        }
                    }
                }
            } else if (dialogButton == 1) {
                JOptionPane.showMessageDialog(null, "Player slected NO and stays in the "
                        + "current country");

            }
        } else if (handle.getTurns() >= 20) {
            JOptionPane.showMessageDialog(null, "Game has finished!");
            JOptionPane.showMessageDialog(null, "The game will now calculate your"
                    + " final score, by taking all of your drugs, sell them in"
                    + " your current country\nand adding the profits to your currency.\n");

            JOptionPane.showMessageDialog(null, "Calculating...");

            //End-Game Sell Drugs
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getCocaineB()) * Integer.parseInt(handle.getCocaine()));
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getAcidB()) * Integer.parseInt(handle.getAcid()));
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getAmphB()) * Integer.parseInt(handle.getAmphetamine()));
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getMethB()) * Integer.parseInt(handle.getMeth()));
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getAngelB()) * Integer.parseInt(handle.getAngeldust()));
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(handle.getHeroinB()) * Integer.parseInt(handle.getHeroin()));

            handle.setHighScore(handle.getCurrentBalance());

            JOptionPane.showMessageDialog(null, "Final Score: " + handle.getHighScore() + "$");
            System.out.println("Final Score: " + handle.getCurrentBalance() + "$");

            //Highscore record
        }


    }//GEN-LAST:event_commitTravelActionPerformed

    private void buyDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyDrugActionPerformed

        int currentPrice = Integer.parseInt(amountBuy.getText()) * handle.getItemPrice();
        if (currentPrice > handle.getCurrentBalance()) {
            JOptionPane.showMessageDialog(null, "Insufficient money!");
        } else if (amountBuy.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Empty Value!");

        } else {
            int dialogButton = JOptionPane.showConfirmDialog(null, "Would you like to "
                    + "buy " + amountBuy.getText() + " Kg of " + handle.getItem() + " Drugs for " + currentPrice + "$?", "Confirm Trade",
                    JOptionPane.YES_NO_OPTION);
            System.out.println(dialogButton);
            if (dialogButton == 0) {
                handle.setCurrentBalance(handle.getCurrentBalance() - currentPrice);
                showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
                handle.items.add(handle.getItem());
                handle.items.add(amountBuy.getText());
                handle.refreshJCombo(sellInv);
                JOptionPane.showMessageDialog(null, "Bought " + amountBuy.getText() + " Kg of Drugs for " + currentPrice + " Dollars$. \n\n Your balance is: " + handle.getCurrentBalance(),
                        "Trade Complete", JOptionPane.NO_OPTION);

                if (handle.getItem().equalsIgnoreCase("Cocaine")) {
                    handle.setCocaineB(Integer.toString(Integer.parseInt(handle.getCocaineB()) + Integer.parseInt(amountBuy.getText())));
                    cocaineKG.setText(handle.getCocaineB());

                    handle.setCocaineWeight(Integer.toString(Integer.parseInt(handle.getCocaineWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgCocaine.setText(handle.getCocaineWeight());
                } else if (handle.getItem().equalsIgnoreCase("Heroin")) {
                    handle.setHeroinB(Integer.toString(Integer.parseInt(handle.getHeroinB()) + Integer.parseInt(amountBuy.getText())));
                    heroinKG.setText(handle.getHeroinB());

                    handle.setHeroinWeight(Integer.toString(Integer.parseInt(handle.getHeroinWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgHeroin.setText(handle.getHeroinWeight());
                } else if (handle.getItem().equalsIgnoreCase("Amphetamine")) {
                    handle.setAmphB(Integer.toString(Integer.parseInt(handle.getAmphB()) + Integer.parseInt(amountBuy.getText())));
                    amphKG.setText(handle.getAmphB());
                    handle.setAmphWeight(Integer.toString(Integer.parseInt(handle.getAmphWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgAmph.setText(handle.getAmphWeight());
                } else if (handle.getItem().equalsIgnoreCase("Acid")) {
                    handle.setAcidB(Integer.toString(Integer.parseInt(handle.getAcidB()) + Integer.parseInt(amountBuy.getText())));
                    acidKG.setText(handle.getAcidB());
                    handle.setAcidWeight(Integer.toString(Integer.parseInt(handle.getAcidWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgAcid.setText(handle.getAcidWeight());
                } else if (handle.getItem().equalsIgnoreCase("Angel Dust")) {
                    handle.setAngelB(Integer.toString(Integer.parseInt(handle.getAngelB()) + Integer.parseInt(amountBuy.getText())));
                    angelKG.setText(handle.getAngelB());
                    handle.setAngeldustWeight(Integer.toString(Integer.parseInt(handle.getAngeldustWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgAngel.setText(handle.getAngeldustWeight());
                } else if (handle.getItem().equalsIgnoreCase("Crystal Meth")) {
                    handle.setMethB(Integer.toString(Integer.parseInt(handle.getMethB()) + Integer.parseInt(amountBuy.getText())));
                    methKG.setText(handle.getMethB());
                    handle.setMethWeight(Integer.toString(Integer.parseInt(handle.getMethWeight()) - Integer.parseInt(amountBuy.getText())));
                    kgMeth.setText(handle.getMethWeight());
                }

            } else if (dialogButton == 1) {
                JOptionPane.showMessageDialog(null, "You've cancelled the trade....",
                        "Trade cancelled", JOptionPane.OK_OPTION);

            }

            System.out.println(handle.getAcid());
            System.out.println(handle.getAmphWeight());
            System.out.println(handle.getAngeldust());
            System.out.println(handle.getCocaine());
            System.out.println(handle.getHeroin());
            System.out.println(handle.getMeth());

        }

    }//GEN-LAST:event_buyDrugActionPerformed

    private void amountBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountBuyActionPerformed

    }//GEN-LAST:event_amountBuyActionPerformed

    private void openHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openHighScoreActionPerformed
        hs.setVisible(true);

    }//GEN-LAST:event_openHighScoreActionPerformed

    private void buyHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyHealthActionPerformed
        int price = 600;
        if (handle.getCurrentBalance() < price) {
            JOptionPane.showMessageDialog(null, "Insufficient Funds!");
        } else if (healthBar.getValue() >= 100) {
            JOptionPane.showMessageDialog(null, "Maximum HP is 100%!");
        } else {
            handle.setCurrentBalance(handle.getCurrentBalance() - price);
            showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
            healthBar.setValue(healthBar.getValue() + 10);
        }
    }//GEN-LAST:event_buyHealthActionPerformed

    private void buyAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAgentsActionPerformed
        int price = 2000;
        if (handle.isAgents() == false) {
            JOptionPane.showMessageDialog(null, "Agents offer special abillities, "
                    + "such as lowering chances of getting caught in customs! "
                    + "Costly, but efficient");

            if (handle.getCurrentBalance() < price) {
                JOptionPane.showMessageDialog(null, "Insufficient Funds!");
            } else if (handle.isAgents() == true) {
                JOptionPane.showMessageDialog(null, "You already have an agent working for you!");
            } else {
                handle.setCurrentBalance(handle.getCurrentBalance() - price);
                showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
                handle.setAgents(true);
                hasAgents.setText("Agents Are Active!");

            }
        } else if (handle.getCurrentBalance() < price) {
            JOptionPane.showMessageDialog(null, "Insufficient Funds!");
        } else if (handle.isAgents() == true) {
            JOptionPane.showMessageDialog(null, "You already have an agent working for you!");
        } else {
            handle.setCurrentBalance(handle.getCurrentBalance() - price);
            showBalance.setText("Current Balance: " + handle.getCurrentBalance() + "$");
            handle.setAgents(true);
        }

    }//GEN-LAST:event_buyAgentsActionPerformed

    private void sellDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellDrugActionPerformed
        if (Integer.parseInt(handle.getCocaineB()) < Integer.parseInt(sellDrugsText.getText())
                || Integer.parseInt(handle.getHeroinB()) < Integer.parseInt(sellDrugsText.getText())
                || Integer.parseInt(handle.getAmphB()) < Integer.parseInt(sellDrugsText.getText())
                || Integer.parseInt(handle.getAcidB()) < Integer.parseInt(sellDrugsText.getText())
                || Integer.parseInt(handle.getAngelB()) < Integer.parseInt(sellDrugsText.getText())
                || Integer.parseInt(handle.getMethB()) < Integer.parseInt(sellDrugsText.getText())) {
            JOptionPane.showMessageDialog(null, "Insufficient Amount Of Drugs!");
        } else if (handle.getItem().equalsIgnoreCase("Cocaine")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getCocaine()));
            handle.setCocaineB(Integer.toString(Integer.parseInt(handle.getCocaineB()) - Integer.parseInt(sellDrugsText.getText())));
            cocaineKG.setText(handle.getCocaineB());
        } else if (handle.getItem().equalsIgnoreCase("Heroin")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getHeroin()));
            handle.setHeroinB(Integer.toString(Integer.parseInt(handle.getHeroinB()) - Integer.parseInt(sellDrugsText.getText())));
            heroinKG.setText(handle.getHeroinB());
        } else if (handle.getItem().equalsIgnoreCase("Amphetamine")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getAmphetamine()));
            handle.setAmphB(Integer.toString(Integer.parseInt(handle.getAmphB()) - Integer.parseInt(sellDrugsText.getText())));
            amphKG.setText(handle.getAmphB());
        } else if (handle.getItem().equalsIgnoreCase("Acid")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getAcid()));
            handle.setAcidB(Integer.toString(Integer.parseInt(handle.getAcidB()) - Integer.parseInt(sellDrugsText.getText())));
            acidKG.setText(handle.getAcidB());
        } else if (handle.getItem().equalsIgnoreCase("Angel Dust")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getAngeldust()));
            handle.setAngelB(Integer.toString(Integer.parseInt(handle.getAngelB()) - Integer.parseInt(sellDrugsText.getText())));
            angelKG.setText(handle.getAngelB());
        } else if (handle.getItem().equalsIgnoreCase("Crystal Meth")) {
            handle.setCurrentBalance(handle.getCurrentBalance() + Integer.parseInt(sellDrugsText.getText()) * Integer.parseInt(handle.getMeth()));
            handle.setMeth(Integer.toString(Integer.parseInt(handle.getMethB()) - Integer.parseInt(sellDrugsText.getText())));
            methKG.setText(handle.getMethB());
        }


    }//GEN-LAST:event_sellDrugActionPerformed

    private void sellInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellInvActionPerformed

    private void sellDrugsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellDrugsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellDrugsTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acidKG;
    private javax.swing.JTextField amountBuy;
    private javax.swing.JLabel amphKG;
    private javax.swing.JLabel angelKG;
    private javax.swing.JButton buyAgents;
    private javax.swing.JButton buyDrug;
    private javax.swing.JButton buyHealth;
    private javax.swing.JLabel cocaineKG;
    private javax.swing.JButton commitTravel;
    private javax.swing.JComboBox<String> countryCombo;
    private javax.swing.JComboBox<String> drugList;
    private javax.swing.JLabel hasAgents;
    private javax.swing.JProgressBar healthBar;
    private javax.swing.JLabel heroinKG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCountryDrugList;
    private javax.swing.JPanel jPanelCountryStash;
    private javax.swing.JPanel jPanelPlayerDrugList;
    private javax.swing.JPanel jPanelPlayerStash;
    private javax.swing.JPanel jPanelPlayerStats;
    private javax.swing.JPanel jPanelTravel;
    private javax.swing.JPanel jPanelVarious;
    private javax.swing.JLabel kgAcid;
    private javax.swing.JLabel kgAmph;
    private javax.swing.JLabel kgAngel;
    private javax.swing.JLabel kgCocaine;
    private javax.swing.JLabel kgHeroin;
    private javax.swing.JLabel kgMeth;
    private javax.swing.JLabel methKG;
    private javax.swing.JButton openHighScore;
    private javax.swing.JButton sellDrug;
    private javax.swing.JTextField sellDrugsText;
    private javax.swing.JComboBox<String> sellInv;
    private javax.swing.JLabel showAcid;
    private javax.swing.JLabel showAmph;
    private javax.swing.JLabel showAngel;
    private javax.swing.JLabel showBalance;
    private javax.swing.JLabel showCocaine;
    private javax.swing.JLabel showCurrentCountry;
    private javax.swing.JLabel showHeroin;
    private javax.swing.JLabel showMeth;
    private javax.swing.JLabel showPlayer;
    private javax.swing.JLabel textShowTurns;
    private javax.swing.JLabel turnsTotal;
    // End of variables declaration//GEN-END:variables
}
